repository_type: pipeline
lint:
  files_exist: false
    - assets/nf-core-tomte_logo_light.png
    - docs/images/nf-core-tomte_logo_light.png
    - docs/images/nf-core-tomte_logo_dark.png
    - docs/images/tomte_pipeline_metromap.eps
  files_unchanged: false
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/email_template.txt
    - docs/README.md
