contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #tomte channel"
    url: https://nfcore.slack.com/channels/tomte
    about: Discussion about the nf-core/tomte pipeline
